redis-pubsub-test done

diff --git a/redis-pubsub-test b/redis-pubsub-test
--- a/redis-pubsub-test
+++ b/redis-pubsub-test
@@ -15,6 +15,7 @@ if [ $? -ne 0 ]; then
 fi
 REDISHOST=localhost
 REDISPORT=6379
+
 while getopts ":h:p:a:" opt
 do
     case ${opt} in
@@ -35,7 +36,7 @@ do
         exit 255
     fi
 	local AUTH=( [password]="$PASSWORD" )
-		if [ "${PASSWORD}" != "" ]; then
+	if [ "${PASSWORD}" != "" ]; then
 		tmpname="array_${RANDOM}"
 		eval "declare -A ${tmpname}"
 		redis_client ${FD} "${tmpname}" AUTH "${PASSWORD}"
@@ -43,24 +44,35 @@ do
 			echo "AUTH command failed"
 			exit 1
 		fi
+		unset ${!tmpname}
 	fi
 
 	tmpname="array_${RANDOM}"
 	eval "declare -A ${tmpname}"
     redis_client ${FD} "${tmpname}" SUBSCRIBE ${1} # subscribe to the pubsub channel in fd ${FD}
+    if [ $? -ne 0 ]; then
+		redis_strval "${tmpname}" STR1
+		echo "Error: SUBSCRIBE command failed: ${STR1}"
+		exit 1
+    fi
+    redis_strval "${tmpname}" STR1 0
+    redis_strval "${tmpname}" STR2 1
+    if [ "${STR1}" != "subscribe" -o "${STR2}" != "${1}" ]; then
+		echo "Error: subscription failed"
+		exit 1
+    fi
+    unset ${!tmpname}
     while true
     do
-        unset ARGV
-        OFS=${IFS};IFS=$'\n' # split the return correctly
-        ARGV=($(redis-client 5))
-        IFS=${OFS}
-        if [ "${ARGV[0]}" = "message" ] && [ "${ARGV[1]}" = "${1}" ]
-        then
-            echo "Message from pubsub channel: ${ARGV[2]}"
-        elif [ -z ${ARGV} ]
-        then
-            sleep 1
-            break
-        fi
+		tmpname="array_${RANDOM}"
+		eval "declare -A ${tmpname}"
+		redis_getreply ${FD} "${tmpname}"
+		redis_strval "${tmpname}" STR1 0
+		redis_strval "${tmpname}" STR2 1
+		if [ "${STR1}" = "message" ] && [ "${STR2}" = "${1}" ]; then
+			redis_strval "${tmpname}" STR3 2
+			echo "Message from pubsub channel: ${STR3}"
+		fi
+		unset ${!tmpname}
     done
 done
